### ISSUE TITLE
0.10 Release Post

### ISSUE THREAD

**Issue by udoprog** [amethyst/documentation#6]
#### What’s Next

Teams to respond:

- [x] Engine
- [x] Rendering
- [x] Networking
- [x] Tools
- [x] Assets
- [x] UI
- [x] Editor
- [x] Documentation
- [x] Community
- [x] Web Team

**Comment by dotellie** [comment]
Rendering team: nothing major planned.
Web team: new website (if that isn't already ready by then)

**Comment by kabergstrom** [comment]
Assets:
[AssetID RFC](https://github.com/amethyst/rfcs/pull/7)
Working on a list of RFCs that are in various stages, should wait with posting more details I think? I have the atelier-assets repo but I don't feel that it's ready to publicize either.
There's the previous [Asset Pipeline discussion](https://github.com/amethyst/amethyst/issues/875) but it became pretty messy to read through, not sure if it's worth to link as a "vision statement".

**Comment by Moxinilian** [comment]
@magnonellie Shouldn't we say a word about the new renderer tho? As it's supposedly going to land in 0.11

**Comment by torkleyy** [comment]
As for Engine:

* More work on `State`s and their interaction with systems
* General usability improvements
    * Look at initialization strategy
    * Work out common patterns & best practices

**Comment by erlend-sh** [comment]
**Community:**
- Refactor contribution guidelines
- Integrate donations with community.amethyst-engine.org

**Comment by TimonPost** [comment]
**Networking**

We’ve been working on [laminar](https://crates.io/crates/laminar) for a while and we’re happy to announce that we released laminar 0.1 November 12, 2018. If you are interested you can check [TWIA 13](https://www.amethyst.rs/blog/twia-13/) out where we introduced our work. 

Now that laminar's first version is released we are ready to put more focus on the amethyst_networking crate. We mostly have been working on the networking roadmap and thinking about some networking concepts. Also, we have integrated laminar into amethyst 0.10. 

If you have some questions, feedback or you just want to be up to date with our work I would recommend to check out the [forums](https://community.amethyst-engine.org/c/development/networking).

**Comment by azriel91** [comment]
Ping @Moxinilian (tools), @jojolepro (UI), @amethyst/editor-team, I'm guessing missing a comment means either "our plan is still being defined", or "we're doing the work to figure out the work", or "we're making changes where it's needed; haven't got a specific focus" or similar.

We're still in that semi-hazy state for docs, so we're not including ourselves in the "What's next" section yet; do you guys have something to add to it?

**Comment by fhaynes** [comment]
Might we include a fundraising link/button/call to action at the bottom?

**Comment by azriel91** [comment]
Added something in, does it match what you had in mind?

**Comment by randomPoison** [comment]
**Editor**:

> We're in the early phases of building prototypes of the editor in order to evaluate different application frameworks. The core application logic is being built out in [amethyst-editor-sync](https://github.com/randomPoison/amethyst-editor-sync), and there is currently a prototype [being built with Electron](https://github.com/randomPoison/amethyst-editor). We are looking at building other prototypes with [Azul](https://azul.rs/) and [orbtk](https://github.com/redox-os/orbtk), and would appreciate contributions from anyone in the community who's interested in experimenting with those (or other) technologies!

If that statement isn't quite what we're looking for, let me know and I can edit/updated it!

**Comment by AnneKitsune** [comment]
Ui Team: 
Moved DrawSprite to DrawFlat2D

Can now directly draw images without a spritesheet using TextureHandle.

Lots of cool things coming up next update.

**Comment by kabergstrom** [comment]
I wrote an overview of approaches to text rendering for the UI team to look at as well, if that's interesting to post about.
https://community.amethyst-engine.org/t/lay-of-the-land-text-rendering/164

**Comment by azriel91** [comment]
Cool, got those all in now

**Comment by AnneKitsune** [comment]
:+1: thanks!

**Comment by LucioFranco** [comment]
This can be closed as 0.10.0 is out. Great work team!!!! ❤️ 🎉
